# Generated by Django 3.2.18 on 2023-05-08 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_auto_20230425_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='update_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
